os: windows
language: go
stages:
  - Build

jobs:
  include:
    - stage: Build
      script: bin/build
      deploy:
        provider: releases
        api_key: $GITHUB_OAUTH_TOKEN
        file: gobackground.exe
        skip_cleanup: true
        on:
          tags: true